trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildTestPublishMain
  steps:
    - script: echo Running CI for main branch
      displayName: 'CI for main branch'

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - script: dotnet restore --verbosity normal
      displayName: 'Restore NuGet packages'

    - script: dotnet build --configuration Release --no-restore
      displayName: 'Build'

    - script: dotnet test --configuration Release --no-build --verbosity normal
      displayName: 'Run Tests'

    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish --no-build
      displayName: 'Publish'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
        artifactName: 'published-app-main'
        publishLocation: 'Container'
